---       
- hosts: client
  become: yes
  tasks:    
    
  - name: Init a new swarm with default parameters
    docker_swarm:
      state: present
    register: join_cmd


  - name: print TOKEN
    debug:
      var: join_cmd.swarm_facts.JoinTokens.Manager
      
    
  - name: Add join cmd to dummy host
    add_host:
      name:   "join_cmd_holder"
      cmd:  "{{ join_cmd.swarm_facts.JoinTokens.Manager }}"
        
        
- hosts: workers
  become: yes
  tasks: 

  - name: print TOKEN
    debug:
      var: hostvars


#   - name: "Join as a manager"
#     become: yes
#     become_user: "root"
#     docker_swarm:
#       state: join
#       join_token: "{{ hostvars['join_cmd_holder']['cmd'] }}"
#       advertise_addr: "{{ ansible_host }}:2377"
#       remote_addrs: ["{{ hostvars[groups.swarm_manager_prime[0]]['ansible_host'] }}:2377" ]
#     retries: 3
#     delay: 15
